name: SnakeAnimation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update user data
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: pecanela
          output_file: dist/github-contribution-grid-snake.svg
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.7.2
        with:
          target_branch: output
          build_dir: dist
          publish_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
